server:
  port: 8091

spring:
  liquibase:
    change-log:
      classpath:/db/changelog/db.changelog-master.yaml
  datasource:
    url: jdbc:h2:file:./db
    username: sa
    password: null
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true

logging:
  livel:
    root:INFO
  file:
    name: src/main/resources/logs/application.log
